### ISSUE TITLE
Add Phases to Feature [feature-add-phases-to-feature]

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes-frontend#525]
### Context

In the recently created Workspace page and Feature page where we need to add a list of phases.

Bounty: https://community.sphinx.chat/bounty/1965

### Design

Clone this branch https://github.com/stakwork/sphinx-tribes-frontend/tree/feature-add-phases-to-feature

Remember to use the components from Elastic UI when ever posible https://eui.elastic.co/

This will be the full Feature page

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/0c92897e-ebf8-4383-8213-c57067895634)

Your job for this issue is to create the 'Phases' part of the page. Here are the specifics.
page: /features/{feature_uuid}

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/54907697/f84986e8-2ec8-46bd-83d2-af9dfeae0476)

Backend Endpoints:

Get list of phases for feature
GET /features/{feature_uuid}/phase

Get phase by uuid
GET /features/{feature_uuid}/phase/{phase_uuid}

Create or Update Phase
POST /features/phase
{
   uuid: '{phase_uuid}', 
   feature_uuid: '{feature_uuid, 
   name: ' {phase name} ', 
   priority: integer
}

Delete Phase
DELETE /features/{feature_uuid}/phase/{phase_uuid}

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a test that creates two new phases, edits a phase and deletes a phase
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by MuhammadUmer44** [comment]
M

**Comment by saithsab877** [comment]
@fvalentiner Could you please assign me?

**Comment by MirzaHanan** [comment]
@fvalentiner  I can help?

**Comment by MahtabBukhari** [comment]
@fvalentiner Could you assign me?

**Comment by MuhammadUmer44** [comment]
HI @fvalentiner , @elraphty
I am trying to create a phase, but I am getting a 401 (Unauthorized) error because @elraphty put a check in the createPhase handler function.

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/160427254/6f091a40-7815-4665-9d3f-326f59d29191)

When I am creating a phase, I am passing a {feature_uuid} that is necessary for getting the feature's phases, but due to the above check, I am getting a 401 error.

![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/160427254/7cb57565-a076-4088-b0dd-78b93ed94002)

**Comment by fvalentiner** [comment]
@MuhammadUmer44 feature_uuid is the uuid of the [feature] not the [phase]. That id should exist. You are creating a phase for a particular feature. You create the phase from the feature page that already has a feature_uuid so use that value to create the new phase

**Comment by MuhammadUmer44** [comment]
@fvalentiner,
Yes, you are right. Please read the above comment. I am saying that due to the check in the backend:
![image](https://github.com/stakwork/sphinx-tribes-frontend/assets/160427254/6f091a40-7815-4665-9d3f-326f59d29191)
When I pass the {feature_uuid} during the create phase to the backend, there is no existing {feature_uuid} in the feature phase database. Due to the check, when I pass the {feature_uuid} from the frontend, it tries to match the {feature_uuid} in the feature phase database. Since there is no existing {feature_uuid} in the feature phase table, I encounter the 401 error.

**Comment by MuhammadUmer44** [comment]
> @MuhammadUmer44 feature_uuid is the uuid of the [feature] not the [phase]. That id should exist. You are creating a phase for a particular feature. You create the phase from the feature page that already has a feature_uuid so use that value to create the new phase

@fvalentiner, yes you are right

**Comment by Ekep-Obasi** [comment]
@fvalentiner please assign me
