### ISSUE TITLE
Unauthorised call when updating profile details

### ISSUE THREAD

**Issue by Nightrider0098** [stakwork/sphinx-tribes-frontend#89]
https://github.com/stakwork/sphinx-tribes-frontend/assets/39752890/f0e3e5c7-ecbc-44e2-8c35-64a4378fc875

**Comment by ecurrencyhodler** [comment]
Thanks for reporting this. It's related to superadmin and how we manage permissions. In the future if someone is added to our admin list, they will be able to access to it. But right now we've completely removed all the restrictions because it's currently being developed. We will be adding users to the restriction list and this will correctly fail or not fail.
